package com.github.arthurramonsouza;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.openfeign.EnableFeignClients;

/**
 * Spring project generated by Spring Initializer.
 * Added dependencies:
 * - Spring Web
 * - Spring Data JPA
 * - H2 Database
 * - OpenFeing
 *  
 *  OpenAPI use Swagger and the dependency was added in pom.xml.
 *  
 * @author ArthurRamonSouza
 *
 */
@EnableFeignClients
@SpringBootApplication
public class DesingtPatternsSpringApplication {

	public static void main(String[] args) {
		SpringApplication.run(DesingtPatternsSpringApplication.class, args);
	}

}
